--
-- PostgreSQL database dump
--

-- Dumped from database version 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: mitre; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA mitre;


ALTER SCHEMA mitre OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cpe; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cpe (
    dtype character varying(31) NOT NULL,
    id character varying(255) NOT NULL,
    edition character varying(255),
    language character varying(255),
    other character varying(255),
    product character varying(255),
    swedition character varying(255),
    targethw character varying(255),
    targetsw character varying(255),
    "Update" character varying(255),
    vendor character varying(255),
    version character varying(255),
    version_end_excluding character varying(255),
    version_end_including character varying(255),
    version_start_excluding character varying(255),
    version_start_including character varying(255),
    vulnerable boolean
);


ALTER TABLE mitre.cpe OWNER TO postgres;

--
-- Name: cpe_compl_cpe; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cpe_compl_cpe (
    compl_cpe_id character varying(255) NOT NULL,
    cpe_id character varying(255) NOT NULL
);


ALTER TABLE mitre.cpe_compl_cpe OWNER TO postgres;

--
-- Name: cve; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cve (
    id character varying(255) NOT NULL,
    cve_data_version character varying(255),
    cvss_v2_base_score double precision NOT NULL,
    cvss_v3_base_score double precision NOT NULL,
    data_format character varying(255),
    data_type character varying(255),
    data_version character varying(255),
    last_modified_date timestamp without time zone,
    meta_data_assigner character varying(255),
    published_date timestamp without time zone,
    cvss_v2_id bigint,
    cvss_v3_id bigint
);


ALTER TABLE mitre.cve OWNER TO postgres;

--
-- Name: cve_descriptions; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cve_descriptions (
    cve_id character varying(255) NOT NULL,
    descriptions character varying(8191)
);


ALTER TABLE mitre.cve_descriptions OWNER TO postgres;

--
-- Name: cvss2; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cvss2 (
    id bigint NOT NULL,
    ac_insuf_info character varying(255),
    access_complexity character varying(255),
    access_vector character varying(255),
    authentication character varying(255),
    availability_impact character varying(255),
    base_score_v2 double precision NOT NULL,
    confidentiality_impact character varying(255),
    exploitability_score_v2 double precision NOT NULL,
    impact_score_v2 double precision NOT NULL,
    integrity_impact character varying(255),
    obtain_all_privilege character varying(255),
    obtain_other_privilege character varying(255),
    obtain_user_privilege character varying(255),
    severity character varying(255),
    user_interaction_required character varying(255),
    vector_string character varying(255),
    version character varying(255)
);


ALTER TABLE mitre.cvss2 OWNER TO postgres;

--
-- Name: cvss2_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cvss2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cvss2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cvss3; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cvss3 (
    id bigint NOT NULL,
    attack_complexity character varying(255),
    attack_vector character varying(255),
    availability_impact character varying(255),
    base_score_v3 double precision NOT NULL,
    base_severity_v3 character varying(255),
    confidentiality_impact character varying(255),
    exploitability_score_v3 double precision NOT NULL,
    impact_score_v3 double precision NOT NULL,
    integrity_impact character varying(255),
    privileges_required character varying(255),
    scope character varying(255),
    user_interaction character varying(255),
    vector_string character varying(255),
    version character varying(255)
);


ALTER TABLE mitre.cvss3 OWNER TO postgres;

--
-- Name: cvss3_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cvss3 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cvss3_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: node; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.node (
    id bigint NOT NULL,
    cve_id character varying(255) NOT NULL
);


ALTER TABLE mitre.node OWNER TO postgres;

--
-- Name: node_compl_cpe; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.node_compl_cpe (
    id character varying(255) NOT NULL,
    cve_id character varying(255),
    vulnerable boolean,
    cpe_id character varying(255),
    node_id bigint
);


ALTER TABLE mitre.node_compl_cpe OWNER TO postgres;

--
-- Name: node_counts; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.node_counts (
    node_id bigint NOT NULL,
    counts integer
);


ALTER TABLE mitre.node_counts OWNER TO postgres;

--
-- Name: node_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.node ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.node_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: node_operators; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.node_operators (
    node_id bigint NOT NULL,
    operators character varying(255)
);


ALTER TABLE mitre.node_operators OWNER TO postgres;

--
-- Name: ref_tags; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.ref_tags (
    reference_id bigint NOT NULL,
    tags character varying(255)
);


ALTER TABLE mitre.ref_tags OWNER TO postgres;

--
-- Name: reference; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.reference (
    id bigint NOT NULL,
    name character varying(8191),
    refsource character varying(255),
    url character varying(8191),
    cve_id character varying(255) NOT NULL
);


ALTER TABLE mitre.reference OWNER TO postgres;

--
-- Name: reference_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.reference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.reference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cpe cpe_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cpe
    ADD CONSTRAINT cpe_pkey PRIMARY KEY (id);


--
-- Name: cve cve_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve
    ADD CONSTRAINT cve_pkey PRIMARY KEY (id);


--
-- Name: cvss2 cvss2_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cvss2
    ADD CONSTRAINT cvss2_pkey PRIMARY KEY (id);


--
-- Name: cvss3 cvss3_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cvss3
    ADD CONSTRAINT cvss3_pkey PRIMARY KEY (id);


--
-- Name: node_compl_cpe node_compl_cpe_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.node_compl_cpe
    ADD CONSTRAINT node_compl_cpe_pkey PRIMARY KEY (id);


--
-- Name: node node_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.node
    ADD CONSTRAINT node_pkey PRIMARY KEY (id);


--
-- Name: reference reference_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.reference
    ADD CONSTRAINT reference_pkey PRIMARY KEY (id);


--
-- Name: cpe_vendor_product_idx; Type: INDEX; Schema: mitre; Owner: postgres
--

CREATE INDEX cpe_vendor_product_idx ON mitre.cpe USING btree (vendor, product);


--
-- Name: cve_descriptions fk7u7qksmh091bcxhpa405soya2; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_descriptions
    ADD CONSTRAINT fk7u7qksmh091bcxhpa405soya2 FOREIGN KEY (cve_id) REFERENCES mitre.cve(id);


--
-- Name: cve fk99froctd1q96xb893dn64hnk4; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve
    ADD CONSTRAINT fk99froctd1q96xb893dn64hnk4 FOREIGN KEY (cvss_v3_id) REFERENCES mitre.cvss3(id);


--
-- Name: cve fk9ie96dqf2c205na5gnba0bfjk; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve
    ADD CONSTRAINT fk9ie96dqf2c205na5gnba0bfjk FOREIGN KEY (cvss_v2_id) REFERENCES mitre.cvss2(id);


--
-- Name: cpe_compl_cpe fka11uua9ih7prslipy95q3vmd3; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cpe_compl_cpe
    ADD CONSTRAINT fka11uua9ih7prslipy95q3vmd3 FOREIGN KEY (cpe_id) REFERENCES mitre.cpe(id);


--
-- Name: node_compl_cpe fkadsvvvrbfpsrwxb5bs5bnok8d; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.node_compl_cpe
    ADD CONSTRAINT fkadsvvvrbfpsrwxb5bs5bnok8d FOREIGN KEY (cpe_id) REFERENCES mitre.cpe(id);


--
-- Name: reference fkb4e53d8qxgq5qs0xixypn02vh; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.reference
    ADD CONSTRAINT fkb4e53d8qxgq5qs0xixypn02vh FOREIGN KEY (cve_id) REFERENCES mitre.cve(id);


--
-- Name: ref_tags fkehe26hyy0nfjjq5fjmyu62orf; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.ref_tags
    ADD CONSTRAINT fkehe26hyy0nfjjq5fjmyu62orf FOREIGN KEY (reference_id) REFERENCES mitre.reference(id);


--
-- Name: node_operators fkgdf155uurjt5otgchm9b9w9cp; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.node_operators
    ADD CONSTRAINT fkgdf155uurjt5otgchm9b9w9cp FOREIGN KEY (node_id) REFERENCES mitre.node(id);


--
-- Name: cpe_compl_cpe fkh3aaw6i6vfv4glpy53acmag0r; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cpe_compl_cpe
    ADD CONSTRAINT fkh3aaw6i6vfv4glpy53acmag0r FOREIGN KEY (compl_cpe_id) REFERENCES mitre.cpe(id);


--
-- Name: node fkjh7xlvevh4eglk8ee25uaw8vf; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.node
    ADD CONSTRAINT fkjh7xlvevh4eglk8ee25uaw8vf FOREIGN KEY (cve_id) REFERENCES mitre.cve(id);


--
-- Name: node_compl_cpe fkp05keyvueo2v3k8b5pjl76oqc; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.node_compl_cpe
    ADD CONSTRAINT fkp05keyvueo2v3k8b5pjl76oqc FOREIGN KEY (node_id) REFERENCES mitre.node(id);


--
-- Name: node_counts fkqjll3na4n1x6xs8egfxe9vc5b; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.node_counts
    ADD CONSTRAINT fkqjll3na4n1x6xs8egfxe9vc5b FOREIGN KEY (node_id) REFERENCES mitre.node(id);


--
-- PostgreSQL database dump complete
--

