--
-- PostgreSQL database dump
--

-- Dumped from database version 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: mitre; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA mitre;


ALTER SCHEMA mitre OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alternate_term; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.alternate_term (
    id bigint NOT NULL,
    description character varying(8191),
    term character varying(255),
    capec_id character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.alternate_term OWNER TO postgres;

--
-- Name: alternate_term_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.alternate_term ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.alternate_term_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: att_step_techniques; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.att_step_techniques (
    capec_attack_step_id bigint NOT NULL,
    technique character varying(8191)
);


ALTER TABLE mitre.att_step_techniques OWNER TO postgres;

--
-- Name: capec; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.capec (
    id character varying(255) NOT NULL,
    attack_likelihood character varying(255),
    capec_abstraction character varying(255),
    capec_name character varying(255),
    capec_status character varying(255),
    description character varying(8191),
    typical_severity character varying(255)
);


ALTER TABLE mitre.capec OWNER TO postgres;

--
-- Name: capec_attack_step; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.capec_attack_step (
    id bigint NOT NULL,
    description character varying(8191),
    phase character varying(255),
    step character varying(255),
    capec_id character varying(255)
);


ALTER TABLE mitre.capec_attack_step OWNER TO postgres;

--
-- Name: capec_attack_step_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.capec_attack_step ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.capec_attack_step_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: capec_examples; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.capec_examples (
    capec_id character varying(255) NOT NULL,
    example character varying(8191)
);


ALTER TABLE mitre.capec_examples OWNER TO postgres;

--
-- Name: capec_indicators; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.capec_indicators (
    capec_id character varying(255) NOT NULL,
    indicator character varying(8191)
);


ALTER TABLE mitre.capec_indicators OWNER TO postgres;

--
-- Name: capec_mitigations; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.capec_mitigations (
    capec_id character varying(255) NOT NULL,
    mitigation character varying(8191)
);


ALTER TABLE mitre.capec_mitigations OWNER TO postgres;

--
-- Name: capec_prerequisites; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.capec_prerequisites (
    capec_id character varying(255) NOT NULL,
    prerequisite character varying(8191)
);


ALTER TABLE mitre.capec_prerequisites OWNER TO postgres;

--
-- Name: capec_resources; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.capec_resources (
    capec_id character varying(255) NOT NULL,
    resource character varying(8191)
);


ALTER TABLE mitre.capec_resources OWNER TO postgres;

--
-- Name: capec_skill; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.capec_skill (
    id bigint NOT NULL,
    content character varying(8191),
    level character varying(255),
    capec_id character varying(255)
);


ALTER TABLE mitre.capec_skill OWNER TO postgres;

--
-- Name: capec_skill_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.capec_skill ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.capec_skill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conseq_impacts; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.conseq_impacts (
    consequence_id bigint NOT NULL,
    impact character varying(255)
);


ALTER TABLE mitre.conseq_impacts OWNER TO postgres;

--
-- Name: conseq_likelihoods; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.conseq_likelihoods (
    consequence_id bigint NOT NULL,
    likelihood character varying(255)
);


ALTER TABLE mitre.conseq_likelihoods OWNER TO postgres;

--
-- Name: conseq_notes; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.conseq_notes (
    consequence_id bigint NOT NULL,
    note character varying(8191)
);


ALTER TABLE mitre.conseq_notes OWNER TO postgres;

--
-- Name: conseq_scopes; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.conseq_scopes (
    consequence_id bigint NOT NULL,
    scope character varying(255)
);


ALTER TABLE mitre.conseq_scopes OWNER TO postgres;

--
-- Name: consequence; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.consequence (
    id bigint NOT NULL,
    capec_id character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.consequence OWNER TO postgres;

--
-- Name: consequence_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.consequence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.consequence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cpe; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cpe (
    dtype character varying(31) NOT NULL,
    id character varying(255) NOT NULL,
    edition character varying(255),
    language character varying(255),
    other character varying(255),
    product character varying(255),
    swedition character varying(255),
    targethw character varying(255),
    targetsw character varying(255),
    "Update" character varying(255),
    vendor character varying(255),
    version character varying(255),
    version_end_excluding character varying(255),
    version_end_including character varying(255),
    version_start_excluding character varying(255),
    version_start_including character varying(255),
    vulnerable boolean
);


ALTER TABLE mitre.cpe OWNER TO postgres;

--
-- Name: cpe_compl_cpe; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cpe_compl_cpe (
    compl_cpe_id character varying(255) NOT NULL,
    cpe_id character varying(255) NOT NULL
);


ALTER TABLE mitre.cpe_compl_cpe OWNER TO postgres;

--
-- Name: cve; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cve (
    id character varying(255) NOT NULL,
    cve_data_version character varying(255),
    cvss_v2_base_score double precision NOT NULL,
    cvss_v3_base_score double precision NOT NULL,
    data_format character varying(255),
    data_type character varying(255),
    data_version character varying(255),
    last_modified_date timestamp without time zone,
    meta_data_assigner character varying(255),
    published_date timestamp without time zone,
    cvss_v2_id bigint,
    cvss_v3_id bigint
);


ALTER TABLE mitre.cve OWNER TO postgres;

--
-- Name: cve_cwe; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cve_cwe (
    cve_id character varying(255) NOT NULL,
    cwe_id character varying(255) NOT NULL
);


ALTER TABLE mitre.cve_cwe OWNER TO postgres;

--
-- Name: cve_descriptions; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cve_descriptions (
    cve_id character varying(255) NOT NULL,
    description character varying(8191)
);


ALTER TABLE mitre.cve_descriptions OWNER TO postgres;

--
-- Name: cve_node; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cve_node (
    id bigint NOT NULL,
    operator character varying(255),
    cve_id character varying(255) NOT NULL,
    parent_id bigint
);


ALTER TABLE mitre.cve_node OWNER TO postgres;

--
-- Name: cve_node_compl_cpe; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cve_node_compl_cpe (
    id character varying(255) NOT NULL,
    cve_id character varying(255),
    vulnerable boolean,
    cpe_id character varying(255),
    node_id bigint
);


ALTER TABLE mitre.cve_node_compl_cpe OWNER TO postgres;

--
-- Name: cve_node_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cve_node ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cve_node_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cve_reference; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cve_reference (
    id bigint NOT NULL,
    name character varying(8191),
    refsource character varying(255),
    url character varying(8191),
    cve_id character varying(255) NOT NULL
);


ALTER TABLE mitre.cve_reference OWNER TO postgres;

--
-- Name: cve_reference_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cve_reference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cve_reference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cvss2; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cvss2 (
    id bigint NOT NULL,
    ac_insuf_info character varying(255),
    access_complexity character varying(255),
    access_vector character varying(255),
    authentication character varying(255),
    availability_impact character varying(255),
    base_score_v2 double precision NOT NULL,
    confidentiality_impact character varying(255),
    exploitability_score_v2 double precision NOT NULL,
    impact_score_v2 double precision NOT NULL,
    integrity_impact character varying(255),
    obtain_all_privilege character varying(255),
    obtain_other_privilege character varying(255),
    obtain_user_privilege character varying(255),
    severity character varying(255),
    user_interaction_required character varying(255),
    vector_string character varying(255),
    version character varying(255)
);


ALTER TABLE mitre.cvss2 OWNER TO postgres;

--
-- Name: cvss2_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cvss2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cvss2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cvss3; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cvss3 (
    id bigint NOT NULL,
    attack_complexity character varying(255),
    attack_vector character varying(255),
    availability_impact character varying(255),
    base_score_v3 double precision NOT NULL,
    base_severity_v3 character varying(255),
    confidentiality_impact character varying(255),
    exploitability_score_v3 double precision NOT NULL,
    impact_score_v3 double precision NOT NULL,
    integrity_impact character varying(255),
    privileges_required character varying(255),
    scope character varying(255),
    user_interaction character varying(255),
    vector_string character varying(255),
    version character varying(255)
);


ALTER TABLE mitre.cvss3 OWNER TO postgres;

--
-- Name: cvss3_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cvss3 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cvss3_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cwe; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe (
    id character varying(255) NOT NULL,
    abstraction character varying(255),
    description character varying(8191),
    exploit_likelihood character varying(255),
    ext_description character varying(8191),
    name character varying(255),
    status character varying(255),
    structure character varying(255)
);


ALTER TABLE mitre.cwe OWNER TO postgres;

--
-- Name: cwe_affected_resources; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe_affected_resources (
    cwe_id character varying(255) NOT NULL,
    affected_resource character varying(255)
);


ALTER TABLE mitre.cwe_affected_resources OWNER TO postgres;

--
-- Name: cwe_applicable_platform; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe_applicable_platform (
    id bigint NOT NULL,
    name character varying(255),
    platform_class character varying(255),
    prevalence character varying(255),
    type character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.cwe_applicable_platform OWNER TO postgres;

--
-- Name: cwe_applicable_platform_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cwe_applicable_platform ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cwe_applicable_platform_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cwe_bg_details; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe_bg_details (
    cwe_id character varying(255) NOT NULL,
    bg_detail character varying(8191)
);


ALTER TABLE mitre.cwe_bg_details OWNER TO postgres;

--
-- Name: cwe_capec; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe_capec (
    cwe_id character varying(255) NOT NULL,
    capec_id character varying(255) NOT NULL
);


ALTER TABLE mitre.cwe_capec OWNER TO postgres;

--
-- Name: cwe_detection_method; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe_detection_method (
    id bigint NOT NULL,
    description character varying(8191),
    effectiveness character varying(255),
    effectiveness_notes character varying(8191),
    method character varying(255),
    method_id character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.cwe_detection_method OWNER TO postgres;

--
-- Name: cwe_detection_method_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cwe_detection_method ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cwe_detection_method_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cwe_functional_areas; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe_functional_areas (
    cwe_id character varying(255) NOT NULL,
    functional_area character varying(255)
);


ALTER TABLE mitre.cwe_functional_areas OWNER TO postgres;

--
-- Name: cwe_introduction; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe_introduction (
    id bigint NOT NULL,
    note character varying(8191),
    phase character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.cwe_introduction OWNER TO postgres;

--
-- Name: cwe_introduction_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cwe_introduction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cwe_introduction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cwe_observed_example; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe_observed_example (
    id bigint NOT NULL,
    description character varying(8191),
    link character varying(8191),
    reference character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.cwe_observed_example OWNER TO postgres;

--
-- Name: cwe_observed_example_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cwe_observed_example ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cwe_observed_example_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cwe_potential_mitigation; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe_potential_mitigation (
    id bigint NOT NULL,
    description character varying(8191),
    effectiveness character varying(255),
    effectiveness_notes character varying(8191),
    mitigation_id character varying(255),
    strategy character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.cwe_potential_mitigation OWNER TO postgres;

--
-- Name: cwe_potential_mitigation_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cwe_potential_mitigation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cwe_potential_mitigation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cwe_weakness_ordinality; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe_weakness_ordinality (
    id bigint NOT NULL,
    description character varying(8191),
    ordinality character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.cwe_weakness_ordinality OWNER TO postgres;

--
-- Name: cwe_weakness_ordinality_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cwe_weakness_ordinality ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cwe_weakness_ordinality_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dem_ex_body_texts; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.dem_ex_body_texts (
    demonstrative_examp_id bigint NOT NULL,
    body_text character varying(8191)
);


ALTER TABLE mitre.dem_ex_body_texts OWNER TO postgres;

--
-- Name: dem_ex_example_code; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.dem_ex_example_code (
    id bigint NOT NULL,
    content character varying(8191),
    language character varying(255),
    nature character varying(255),
    dem_ex_id bigint
);


ALTER TABLE mitre.dem_ex_example_code OWNER TO postgres;

--
-- Name: dem_ex_example_code_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.dem_ex_example_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.dem_ex_example_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demonstrative_examp; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.demonstrative_examp (
    id bigint NOT NULL,
    intro_text character varying(8191),
    cwe_id character varying(255)
);


ALTER TABLE mitre.demonstrative_examp OWNER TO postgres;

--
-- Name: demonstrative_examp_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.demonstrative_examp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.demonstrative_examp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ext_ref_authors; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.ext_ref_authors (
    external_reference_id character varying(255) NOT NULL,
    author character varying(255)
);


ALTER TABLE mitre.ext_ref_authors OWNER TO postgres;

--
-- Name: external_ref_ref; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.external_ref_ref (
    id bigint NOT NULL,
    section character varying(255),
    capec_id character varying(255),
    cwe_id character varying(255),
    dem_ex_id bigint,
    ext_ref_id character varying(255)
);


ALTER TABLE mitre.external_ref_ref OWNER TO postgres;

--
-- Name: external_ref_ref_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.external_ref_ref ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.external_ref_ref_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: external_reference; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.external_reference (
    id character varying(255) NOT NULL,
    edition character varying(255),
    publication character varying(255),
    publication_date timestamp without time zone,
    publisher character varying(255),
    title character varying(255),
    url character varying(255),
    url_date timestamp without time zone
);


ALTER TABLE mitre.external_reference OWNER TO postgres;

--
-- Name: note; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.note (
    id bigint NOT NULL,
    note_content character varying(8191),
    type character varying(255),
    capec_id character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.note OWNER TO postgres;

--
-- Name: note_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.note ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.note_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pot_mit_phases; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.pot_mit_phases (
    cwe_potential_mitigation_id bigint NOT NULL,
    phase character varying(255)
);


ALTER TABLE mitre.pot_mit_phases OWNER TO postgres;

--
-- Name: ref_tags; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.ref_tags (
    cve_reference_id bigint NOT NULL,
    tag character varying(255)
);


ALTER TABLE mitre.ref_tags OWNER TO postgres;

--
-- Name: rel_capec_exclude_ids; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.rel_capec_exclude_ids (
    related_attack_pattern_id bigint NOT NULL,
    exclude_id character varying(255)
);


ALTER TABLE mitre.rel_capec_exclude_ids OWNER TO postgres;

--
-- Name: related_attack_pattern; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.related_attack_pattern (
    id bigint NOT NULL,
    nature character varying(255),
    capec_id character varying(255),
    related_capec_id character varying(255)
);


ALTER TABLE mitre.related_attack_pattern OWNER TO postgres;

--
-- Name: related_attack_pattern_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.related_attack_pattern ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.related_attack_pattern_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: related_weakness; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.related_weakness (
    id bigint NOT NULL,
    nature character varying(255),
    ordinal character varying(255),
    view_id character varying(255),
    cwe_id character varying(255),
    related_cwe_id character varying(255)
);


ALTER TABLE mitre.related_weakness OWNER TO postgres;

--
-- Name: related_weakness_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.related_weakness ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.related_weakness_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: taxonomy_mapping; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.taxonomy_mapping (
    id bigint NOT NULL,
    entry_id character varying(255),
    entry_name character varying(255),
    mapping_fit character varying(255),
    name character varying(255),
    capec_id character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.taxonomy_mapping OWNER TO postgres;

--
-- Name: taxonomy_mapping_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.taxonomy_mapping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.taxonomy_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alternate_term alternate_term_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.alternate_term
    ADD CONSTRAINT alternate_term_pkey PRIMARY KEY (id);


--
-- Name: capec_attack_step capec_attack_step_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.capec_attack_step
    ADD CONSTRAINT capec_attack_step_pkey PRIMARY KEY (id);


--
-- Name: capec capec_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.capec
    ADD CONSTRAINT capec_pkey PRIMARY KEY (id);


--
-- Name: capec_skill capec_skill_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.capec_skill
    ADD CONSTRAINT capec_skill_pkey PRIMARY KEY (id);


--
-- Name: consequence consequence_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.consequence
    ADD CONSTRAINT consequence_pkey PRIMARY KEY (id);


--
-- Name: cpe cpe_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cpe
    ADD CONSTRAINT cpe_pkey PRIMARY KEY (id);


--
-- Name: cve_node_compl_cpe cve_node_compl_cpe_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_node_compl_cpe
    ADD CONSTRAINT cve_node_compl_cpe_pkey PRIMARY KEY (id);


--
-- Name: cve_node cve_node_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_node
    ADD CONSTRAINT cve_node_pkey PRIMARY KEY (id);


--
-- Name: cve cve_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve
    ADD CONSTRAINT cve_pkey PRIMARY KEY (id);


--
-- Name: cve_reference cve_reference_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_reference
    ADD CONSTRAINT cve_reference_pkey PRIMARY KEY (id);


--
-- Name: cvss2 cvss2_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cvss2
    ADD CONSTRAINT cvss2_pkey PRIMARY KEY (id);


--
-- Name: cvss3 cvss3_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cvss3
    ADD CONSTRAINT cvss3_pkey PRIMARY KEY (id);


--
-- Name: cwe_applicable_platform cwe_applicable_platform_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_applicable_platform
    ADD CONSTRAINT cwe_applicable_platform_pkey PRIMARY KEY (id);


--
-- Name: cwe_detection_method cwe_detection_method_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_detection_method
    ADD CONSTRAINT cwe_detection_method_pkey PRIMARY KEY (id);


--
-- Name: cwe_introduction cwe_introduction_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_introduction
    ADD CONSTRAINT cwe_introduction_pkey PRIMARY KEY (id);


--
-- Name: cwe_observed_example cwe_observed_example_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_observed_example
    ADD CONSTRAINT cwe_observed_example_pkey PRIMARY KEY (id);


--
-- Name: cwe cwe_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe
    ADD CONSTRAINT cwe_pkey PRIMARY KEY (id);


--
-- Name: cwe_potential_mitigation cwe_potential_mitigation_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_potential_mitigation
    ADD CONSTRAINT cwe_potential_mitigation_pkey PRIMARY KEY (id);


--
-- Name: cwe_weakness_ordinality cwe_weakness_ordinality_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_weakness_ordinality
    ADD CONSTRAINT cwe_weakness_ordinality_pkey PRIMARY KEY (id);


--
-- Name: dem_ex_example_code dem_ex_example_code_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.dem_ex_example_code
    ADD CONSTRAINT dem_ex_example_code_pkey PRIMARY KEY (id);


--
-- Name: demonstrative_examp demonstrative_examp_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.demonstrative_examp
    ADD CONSTRAINT demonstrative_examp_pkey PRIMARY KEY (id);


--
-- Name: external_ref_ref external_ref_ref_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.external_ref_ref
    ADD CONSTRAINT external_ref_ref_pkey PRIMARY KEY (id);


--
-- Name: external_reference external_reference_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.external_reference
    ADD CONSTRAINT external_reference_pkey PRIMARY KEY (id);


--
-- Name: note note_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.note
    ADD CONSTRAINT note_pkey PRIMARY KEY (id);


--
-- Name: related_attack_pattern related_attack_pattern_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.related_attack_pattern
    ADD CONSTRAINT related_attack_pattern_pkey PRIMARY KEY (id);


--
-- Name: related_weakness related_weakness_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.related_weakness
    ADD CONSTRAINT related_weakness_pkey PRIMARY KEY (id);


--
-- Name: taxonomy_mapping taxonomy_mapping_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.taxonomy_mapping
    ADD CONSTRAINT taxonomy_mapping_pkey PRIMARY KEY (id);


--
-- Name: cpe_vendor_product_idx; Type: INDEX; Schema: mitre; Owner: postgres
--

CREATE INDEX cpe_vendor_product_idx ON mitre.cpe USING btree (vendor, product);


--
-- Name: att_step_techniques fk1l3hikb94k0somvvt3a266rxe; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.att_step_techniques
    ADD CONSTRAINT fk1l3hikb94k0somvvt3a266rxe FOREIGN KEY (capec_attack_step_id) REFERENCES mitre.capec_attack_step(id);


--
-- Name: dem_ex_example_code fk2jho9mrhbybrglxu1vohducb2; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.dem_ex_example_code
    ADD CONSTRAINT fk2jho9mrhbybrglxu1vohducb2 FOREIGN KEY (dem_ex_id) REFERENCES mitre.demonstrative_examp(id);


--
-- Name: cve_node_compl_cpe fk2oxi5qipxgg71chwttue8ggn1; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_node_compl_cpe
    ADD CONSTRAINT fk2oxi5qipxgg71chwttue8ggn1 FOREIGN KEY (node_id) REFERENCES mitre.cve_node(id);


--
-- Name: cve_node_compl_cpe fk34h49h5ky0rikypsvf1g6k58a; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_node_compl_cpe
    ADD CONSTRAINT fk34h49h5ky0rikypsvf1g6k58a FOREIGN KEY (cpe_id) REFERENCES mitre.cpe(id);


--
-- Name: capec_mitigations fk3p4uk2cv10m7e647bot9acpgo; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.capec_mitigations
    ADD CONSTRAINT fk3p4uk2cv10m7e647bot9acpgo FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: conseq_notes fk3st0yvoglvedogk1nnke9ws8y; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.conseq_notes
    ADD CONSTRAINT fk3st0yvoglvedogk1nnke9ws8y FOREIGN KEY (consequence_id) REFERENCES mitre.consequence(id);


--
-- Name: alternate_term fk3tw5p2e90p2me836td5y0pw3n; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.alternate_term
    ADD CONSTRAINT fk3tw5p2e90p2me836td5y0pw3n FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: cwe_detection_method fk4msa150cti0mh2b4h5i0aou3g; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_detection_method
    ADD CONSTRAINT fk4msa150cti0mh2b4h5i0aou3g FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: external_ref_ref fk65olsm4uxrdxnijpkjtojpdsn; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.external_ref_ref
    ADD CONSTRAINT fk65olsm4uxrdxnijpkjtojpdsn FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: dem_ex_body_texts fk6cdw4c073yamaeyv3yqfhakkd; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.dem_ex_body_texts
    ADD CONSTRAINT fk6cdw4c073yamaeyv3yqfhakkd FOREIGN KEY (demonstrative_examp_id) REFERENCES mitre.demonstrative_examp(id);


--
-- Name: cwe_observed_example fk6mrkohx92cq0wkcr4s70qp9f; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_observed_example
    ADD CONSTRAINT fk6mrkohx92cq0wkcr4s70qp9f FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: cve_node fk6nmwvmkn8h924nsbwi8jn4to3; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_node
    ADD CONSTRAINT fk6nmwvmkn8h924nsbwi8jn4to3 FOREIGN KEY (cve_id) REFERENCES mitre.cve(id);


--
-- Name: cwe_capec fk6ovdygmh071weon17p33mhm6h; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_capec
    ADD CONSTRAINT fk6ovdygmh071weon17p33mhm6h FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: conseq_scopes fk7elh28fnn31crwfghykdvogk5; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.conseq_scopes
    ADD CONSTRAINT fk7elh28fnn31crwfghykdvogk5 FOREIGN KEY (consequence_id) REFERENCES mitre.consequence(id);


--
-- Name: consequence fk7kjbqloyrva4qommg8a80nlbj; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.consequence
    ADD CONSTRAINT fk7kjbqloyrva4qommg8a80nlbj FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: cve_descriptions fk7u7qksmh091bcxhpa405soya2; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_descriptions
    ADD CONSTRAINT fk7u7qksmh091bcxhpa405soya2 FOREIGN KEY (cve_id) REFERENCES mitre.cve(id);


--
-- Name: cve fk99froctd1q96xb893dn64hnk4; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve
    ADD CONSTRAINT fk99froctd1q96xb893dn64hnk4 FOREIGN KEY (cvss_v3_id) REFERENCES mitre.cvss3(id);


--
-- Name: cve fk9ie96dqf2c205na5gnba0bfjk; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve
    ADD CONSTRAINT fk9ie96dqf2c205na5gnba0bfjk FOREIGN KEY (cvss_v2_id) REFERENCES mitre.cvss2(id);


--
-- Name: cpe_compl_cpe fka11uua9ih7prslipy95q3vmd3; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cpe_compl_cpe
    ADD CONSTRAINT fka11uua9ih7prslipy95q3vmd3 FOREIGN KEY (cpe_id) REFERENCES mitre.cpe(id);


--
-- Name: external_ref_ref fka5dherbgqsvx1ehmxququqb0w; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.external_ref_ref
    ADD CONSTRAINT fka5dherbgqsvx1ehmxququqb0w FOREIGN KEY (dem_ex_id) REFERENCES mitre.demonstrative_examp(id);


--
-- Name: related_weakness fkasq6nip9axffe09ciehdid4xd; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.related_weakness
    ADD CONSTRAINT fkasq6nip9axffe09ciehdid4xd FOREIGN KEY (related_cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: taxonomy_mapping fkaypssanst11ikkjk2mka33x3n; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.taxonomy_mapping
    ADD CONSTRAINT fkaypssanst11ikkjk2mka33x3n FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: cwe_introduction fkcakxtctj3oethqvxotjtsg8kc; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_introduction
    ADD CONSTRAINT fkcakxtctj3oethqvxotjtsg8kc FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: cwe_applicable_platform fkdslvvfkqhu04istb3hv7uspht; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_applicable_platform
    ADD CONSTRAINT fkdslvvfkqhu04istb3hv7uspht FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: ref_tags fke8dtjcdkom0cktpsyunohgo0b; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.ref_tags
    ADD CONSTRAINT fke8dtjcdkom0cktpsyunohgo0b FOREIGN KEY (cve_reference_id) REFERENCES mitre.cve_reference(id);


--
-- Name: capec_indicators fkek1jdcbqugo4ieajg3ejs03vq; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.capec_indicators
    ADD CONSTRAINT fkek1jdcbqugo4ieajg3ejs03vq FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: cwe_weakness_ordinality fkesxsqjvnvk1avq4843amhqgg5; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_weakness_ordinality
    ADD CONSTRAINT fkesxsqjvnvk1avq4843amhqgg5 FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: note fkfbu55jlellxyinodttvyf8afx; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.note
    ADD CONSTRAINT fkfbu55jlellxyinodttvyf8afx FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: cve_cwe fkfkposkqwsla5viief2dljgbax; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_cwe
    ADD CONSTRAINT fkfkposkqwsla5viief2dljgbax FOREIGN KEY (cve_id) REFERENCES mitre.cve(id);


--
-- Name: cwe_functional_areas fkggxh7xviwbm8h5l02giarpek5; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_functional_areas
    ADD CONSTRAINT fkggxh7xviwbm8h5l02giarpek5 FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: cpe_compl_cpe fkh3aaw6i6vfv4glpy53acmag0r; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cpe_compl_cpe
    ADD CONSTRAINT fkh3aaw6i6vfv4glpy53acmag0r FOREIGN KEY (compl_cpe_id) REFERENCES mitre.cpe(id);


--
-- Name: cwe_affected_resources fkhidlbsyc6qhqdmdmfwiw5llyq; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_affected_resources
    ADD CONSTRAINT fkhidlbsyc6qhqdmdmfwiw5llyq FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: consequence fkiyuk4wmvf24dw6yx1yus3s2a5; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.consequence
    ADD CONSTRAINT fkiyuk4wmvf24dw6yx1yus3s2a5 FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: capec_skill fkj4ovq0amec5wgvr57kpfdhqqo; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.capec_skill
    ADD CONSTRAINT fkj4ovq0amec5wgvr57kpfdhqqo FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: conseq_impacts fkje76yafdsx5ge9b6f5yo8g9d4; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.conseq_impacts
    ADD CONSTRAINT fkje76yafdsx5ge9b6f5yo8g9d4 FOREIGN KEY (consequence_id) REFERENCES mitre.consequence(id);


--
-- Name: taxonomy_mapping fkkm3jgwg7r41ymei32ma9d7okq; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.taxonomy_mapping
    ADD CONSTRAINT fkkm3jgwg7r41ymei32ma9d7okq FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: conseq_likelihoods fklqo3f0911td36bwwqx3aggtpv; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.conseq_likelihoods
    ADD CONSTRAINT fklqo3f0911td36bwwqx3aggtpv FOREIGN KEY (consequence_id) REFERENCES mitre.consequence(id);


--
-- Name: cve_node fklrauuhfb9aghdhfnoqwddordo; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_node
    ADD CONSTRAINT fklrauuhfb9aghdhfnoqwddordo FOREIGN KEY (parent_id) REFERENCES mitre.cve_node(id);


--
-- Name: cwe_bg_details fkmer4l6copp7d65eobk4h7iop4; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_bg_details
    ADD CONSTRAINT fkmer4l6copp7d65eobk4h7iop4 FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: cwe_capec fkmkdjj0qpout9t9cs2ccqgx8vt; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_capec
    ADD CONSTRAINT fkmkdjj0qpout9t9cs2ccqgx8vt FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: capec_examples fkn0mb2l9q9e6eiuqmstosqbgbr; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.capec_examples
    ADD CONSTRAINT fkn0mb2l9q9e6eiuqmstosqbgbr FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: related_attack_pattern fknjvufdaenwpewc4xsl00m4fse; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.related_attack_pattern
    ADD CONSTRAINT fknjvufdaenwpewc4xsl00m4fse FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: external_ref_ref fkobvh60wu8bulfcpfkqv61w3wk; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.external_ref_ref
    ADD CONSTRAINT fkobvh60wu8bulfcpfkqv61w3wk FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: cve_reference fkoxhr5rwd9da5xlj5476tprkeb; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_reference
    ADD CONSTRAINT fkoxhr5rwd9da5xlj5476tprkeb FOREIGN KEY (cve_id) REFERENCES mitre.cve(id);


--
-- Name: capec_resources fkpcy4ig2bffxg22gf6fn9lsu6n; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.capec_resources
    ADD CONSTRAINT fkpcy4ig2bffxg22gf6fn9lsu6n FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: capec_attack_step fkqdxqw8fwlucnw9tef9k2khc3o; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.capec_attack_step
    ADD CONSTRAINT fkqdxqw8fwlucnw9tef9k2khc3o FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: cwe_potential_mitigation fkquyvxm0epxt6n7ql7on0m3okf; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_potential_mitigation
    ADD CONSTRAINT fkquyvxm0epxt6n7ql7on0m3okf FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: rel_capec_exclude_ids fkr77bibr4ib9da4epmv6n3alis; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.rel_capec_exclude_ids
    ADD CONSTRAINT fkr77bibr4ib9da4epmv6n3alis FOREIGN KEY (related_attack_pattern_id) REFERENCES mitre.related_attack_pattern(id);


--
-- Name: external_ref_ref fkrbd28ykduxxrtsh54wkg8flp0; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.external_ref_ref
    ADD CONSTRAINT fkrbd28ykduxxrtsh54wkg8flp0 FOREIGN KEY (ext_ref_id) REFERENCES mitre.external_reference(id);


--
-- Name: ext_ref_authors fkrpt9drh5fmis6m3wg0gtjq1b5; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.ext_ref_authors
    ADD CONSTRAINT fkrpt9drh5fmis6m3wg0gtjq1b5 FOREIGN KEY (external_reference_id) REFERENCES mitre.external_reference(id);


--
-- Name: cve_cwe fksu7avj0pjcgrhiu7sr9er4tyd; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_cwe
    ADD CONSTRAINT fksu7avj0pjcgrhiu7sr9er4tyd FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: related_weakness fkswd4roskn4w9yggcd99l9jtie; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.related_weakness
    ADD CONSTRAINT fkswd4roskn4w9yggcd99l9jtie FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: related_attack_pattern fksyh451ole8qnof69v681d0hm3; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.related_attack_pattern
    ADD CONSTRAINT fksyh451ole8qnof69v681d0hm3 FOREIGN KEY (related_capec_id) REFERENCES mitre.capec(id);


--
-- Name: note fkta4moqqyeyd0i9lqjq8t7kbnu; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.note
    ADD CONSTRAINT fkta4moqqyeyd0i9lqjq8t7kbnu FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: pot_mit_phases fktdqlj7h7gn1q4kval1vktyeo9; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.pot_mit_phases
    ADD CONSTRAINT fktdqlj7h7gn1q4kval1vktyeo9 FOREIGN KEY (cwe_potential_mitigation_id) REFERENCES mitre.cwe_potential_mitigation(id);


--
-- Name: capec_prerequisites fktkp1um17xlx3on6d1phgp8p9c; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.capec_prerequisites
    ADD CONSTRAINT fktkp1um17xlx3on6d1phgp8p9c FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: demonstrative_examp fktlwod5w3aujwd2inxoo3lkdju; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.demonstrative_examp
    ADD CONSTRAINT fktlwod5w3aujwd2inxoo3lkdju FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: alternate_term fktmpr3n7fjsgx7alvxvthi1phq; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.alternate_term
    ADD CONSTRAINT fktmpr3n7fjsgx7alvxvthi1phq FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- PostgreSQL database dump complete
--

