--
-- PostgreSQL database dump
--

-- Dumped from database version 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: mitre; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA mitre;


ALTER SCHEMA mitre OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: affected_resources; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.affected_resources (
    cwe_id character varying(255) NOT NULL,
    affected_resource character varying(255)
);


ALTER TABLE mitre.affected_resources OWNER TO postgres;

--
-- Name: alternate_term; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.alternate_term (
    id bigint NOT NULL,
    description character varying(8191),
    term character varying(255),
    capec_id character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.alternate_term OWNER TO postgres;

--
-- Name: alternate_term_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.alternate_term ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.alternate_term_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: applicable_platform; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.applicable_platform (
    id bigint NOT NULL,
    name character varying(255),
    platform_class character varying(255),
    prevalence character varying(255),
    type character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.applicable_platform OWNER TO postgres;

--
-- Name: applicable_platform_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.applicable_platform ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.applicable_platform_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attack_step; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.attack_step (
    id bigint NOT NULL,
    description character varying(8191),
    phase character varying(255),
    step character varying(255),
    capec_id character varying(255)
);


ALTER TABLE mitre.attack_step OWNER TO postgres;

--
-- Name: attack_step_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.attack_step ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.attack_step_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bg_details; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.bg_details (
    cwe_id character varying(255) NOT NULL,
    bg_detail character varying(8191)
);


ALTER TABLE mitre.bg_details OWNER TO postgres;

--
-- Name: body_texts; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.body_texts (
    demonstrative_examp_id bigint NOT NULL,
    body_text character varying(8191)
);


ALTER TABLE mitre.body_texts OWNER TO postgres;

--
-- Name: capec; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.capec (
    id character varying(255) NOT NULL,
    attack_likelihood character varying(255),
    capec_abstraction character varying(255),
    capec_name character varying(255),
    capec_status character varying(255),
    description character varying(8191),
    typical_severity character varying(255)
);


ALTER TABLE mitre.capec OWNER TO postgres;

--
-- Name: capec_relation; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.capec_relation (
    id bigint NOT NULL,
    nature character varying(255),
    related_capec_id character varying(255),
    capec_id character varying(255)
);


ALTER TABLE mitre.capec_relation OWNER TO postgres;

--
-- Name: capec_relation_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.capec_relation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.capec_relation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consequence; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.consequence (
    id bigint NOT NULL,
    capec_id character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.consequence OWNER TO postgres;

--
-- Name: consequence_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.consequence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.consequence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consequence_notes; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.consequence_notes (
    consequence_id bigint NOT NULL,
    note character varying(8191)
);


ALTER TABLE mitre.consequence_notes OWNER TO postgres;

--
-- Name: cpe; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cpe (
    dtype character varying(31) NOT NULL,
    id character varying(255) NOT NULL,
    edition character varying(255),
    language character varying(255),
    other character varying(255),
    product character varying(255),
    swedition character varying(255),
    targethw character varying(255),
    targetsw character varying(255),
    "Update" character varying(255),
    vendor character varying(255),
    version character varying(255),
    version_end_excluding character varying(255),
    version_end_including character varying(255),
    version_start_excluding character varying(255),
    version_start_including character varying(255),
    vulnerable boolean
);


ALTER TABLE mitre.cpe OWNER TO postgres;

--
-- Name: cpe_compl_cpe; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cpe_compl_cpe (
    compl_cpe_id character varying(255) NOT NULL,
    cpe_id character varying(255) NOT NULL
);


ALTER TABLE mitre.cpe_compl_cpe OWNER TO postgres;

--
-- Name: cve; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cve (
    id character varying(255) NOT NULL,
    cve_data_version character varying(255),
    cvss_v2_base_score double precision NOT NULL,
    cvss_v3_base_score double precision NOT NULL,
    data_format character varying(255),
    data_type character varying(255),
    data_version character varying(255),
    last_modified_date timestamp without time zone,
    meta_data_assigner character varying(255),
    published_date timestamp without time zone,
    cvss_v2_id bigint,
    cvss_v3_id bigint
);


ALTER TABLE mitre.cve OWNER TO postgres;

--
-- Name: cve_cwe; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cve_cwe (
    cve_id character varying(255) NOT NULL,
    cwe_id character varying(255) NOT NULL
);


ALTER TABLE mitre.cve_cwe OWNER TO postgres;

--
-- Name: cvss2; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cvss2 (
    id bigint NOT NULL,
    ac_insuf_info character varying(255),
    access_complexity character varying(255),
    access_vector character varying(255),
    authentication character varying(255),
    availability_impact character varying(255),
    base_score_v2 double precision NOT NULL,
    confidentiality_impact character varying(255),
    exploitability_score_v2 double precision NOT NULL,
    impact_score_v2 double precision NOT NULL,
    integrity_impact character varying(255),
    obtain_all_privilege character varying(255),
    obtain_other_privilege character varying(255),
    obtain_user_privilege character varying(255),
    severity character varying(255),
    user_interaction_required character varying(255),
    vector_string character varying(255),
    version character varying(255)
);


ALTER TABLE mitre.cvss2 OWNER TO postgres;

--
-- Name: cvss2_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cvss2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cvss2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cvss3; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cvss3 (
    id bigint NOT NULL,
    attack_complexity character varying(255),
    attack_vector character varying(255),
    availability_impact character varying(255),
    base_score_v3 double precision NOT NULL,
    base_severity_v3 character varying(255),
    confidentiality_impact character varying(255),
    exploitability_score_v3 double precision NOT NULL,
    impact_score_v3 double precision NOT NULL,
    integrity_impact character varying(255),
    privileges_required character varying(255),
    scope character varying(255),
    user_interaction character varying(255),
    vector_string character varying(255),
    version character varying(255)
);


ALTER TABLE mitre.cvss3 OWNER TO postgres;

--
-- Name: cvss3_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cvss3 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cvss3_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cwe; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe (
    id character varying(255) NOT NULL,
    abstraction character varying(255),
    description character varying(8191),
    exploit_likelihood character varying(255),
    ext_description character varying(8191),
    name character varying(255),
    status character varying(255),
    structure character varying(255)
);


ALTER TABLE mitre.cwe OWNER TO postgres;

--
-- Name: cwe_capec; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe_capec (
    cwe_id character varying(255) NOT NULL,
    capec_id character varying(255) NOT NULL
);


ALTER TABLE mitre.cwe_capec OWNER TO postgres;

--
-- Name: cwe_relation; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.cwe_relation (
    id bigint NOT NULL,
    nature character varying(255),
    ordinal character varying(255),
    related_cwe_id character varying(255),
    view_id character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.cwe_relation OWNER TO postgres;

--
-- Name: cwe_relation_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.cwe_relation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.cwe_relation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demonstrative_examp; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.demonstrative_examp (
    id bigint NOT NULL,
    intro_text character varying(8191),
    cwe_id character varying(255)
);


ALTER TABLE mitre.demonstrative_examp OWNER TO postgres;

--
-- Name: demonstrative_examp_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.demonstrative_examp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.demonstrative_examp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: descriptions; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.descriptions (
    cve_id character varying(255) NOT NULL,
    description character varying(8191)
);


ALTER TABLE mitre.descriptions OWNER TO postgres;

--
-- Name: detection_method; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.detection_method (
    id bigint NOT NULL,
    description character varying(8191),
    effectiveness character varying(255),
    effectiveness_notes character varying(8191),
    method character varying(255),
    method_id character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.detection_method OWNER TO postgres;

--
-- Name: detection_method_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.detection_method ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.detection_method_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: example_code; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.example_code (
    id bigint NOT NULL,
    content character varying(8191),
    language character varying(255),
    nature character varying(255),
    dem_ex_id bigint
);


ALTER TABLE mitre.example_code OWNER TO postgres;

--
-- Name: example_code_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.example_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.example_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: examples; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.examples (
    capec_id character varying(255) NOT NULL,
    example character varying(8191)
);


ALTER TABLE mitre.examples OWNER TO postgres;

--
-- Name: exclude_ids; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.exclude_ids (
    capec_relation_id bigint NOT NULL,
    exclude_id character varying(255)
);


ALTER TABLE mitre.exclude_ids OWNER TO postgres;

--
-- Name: external_ref_ref; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.external_ref_ref (
    id bigint NOT NULL,
    ext_ref_id character varying(255),
    section character varying(255),
    capec_id character varying(255),
    cwe_id character varying(255),
    dem_ex_id bigint
);


ALTER TABLE mitre.external_ref_ref OWNER TO postgres;

--
-- Name: external_ref_ref_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.external_ref_ref ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.external_ref_ref_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: functional_areas; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.functional_areas (
    cwe_id character varying(255) NOT NULL,
    functional_area character varying(255)
);


ALTER TABLE mitre.functional_areas OWNER TO postgres;

--
-- Name: impacts; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.impacts (
    consequence_id bigint NOT NULL,
    impact character varying(255)
);


ALTER TABLE mitre.impacts OWNER TO postgres;

--
-- Name: indicators; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.indicators (
    capec_id character varying(255) NOT NULL,
    indicator character varying(8191)
);


ALTER TABLE mitre.indicators OWNER TO postgres;

--
-- Name: introduction; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.introduction (
    id bigint NOT NULL,
    note character varying(8191),
    phase character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.introduction OWNER TO postgres;

--
-- Name: introduction_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.introduction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.introduction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: likelihoods; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.likelihoods (
    consequence_id bigint NOT NULL,
    likelihood character varying(255)
);


ALTER TABLE mitre.likelihoods OWNER TO postgres;

--
-- Name: mitigations; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.mitigations (
    capec_id character varying(255) NOT NULL,
    mitigation character varying(8191)
);


ALTER TABLE mitre.mitigations OWNER TO postgres;

--
-- Name: node; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.node (
    id bigint NOT NULL,
    operator character varying(255),
    cve_id character varying(255) NOT NULL,
    parent_id bigint
);


ALTER TABLE mitre.node OWNER TO postgres;

--
-- Name: node_compl_cpe; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.node_compl_cpe (
    id character varying(255) NOT NULL,
    cve_id character varying(255),
    vulnerable boolean,
    cpe_id character varying(255),
    node_id bigint
);


ALTER TABLE mitre.node_compl_cpe OWNER TO postgres;

--
-- Name: node_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.node ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.node_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: note; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.note (
    id bigint NOT NULL,
    note_content character varying(8191),
    type character varying(255),
    capec_id character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.note OWNER TO postgres;

--
-- Name: note_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.note ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.note_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: observed_example; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.observed_example (
    id bigint NOT NULL,
    description character varying(8191),
    link character varying(8191),
    reference character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.observed_example OWNER TO postgres;

--
-- Name: observed_example_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.observed_example ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.observed_example_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: phases; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.phases (
    potential_mitigation_id bigint NOT NULL,
    phase character varying(255)
);


ALTER TABLE mitre.phases OWNER TO postgres;

--
-- Name: potential_mitigation; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.potential_mitigation (
    id bigint NOT NULL,
    description character varying(8191),
    effectiveness character varying(255),
    effectiveness_notes character varying(8191),
    mitigation_id character varying(255),
    strategy character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.potential_mitigation OWNER TO postgres;

--
-- Name: potential_mitigation_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.potential_mitigation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.potential_mitigation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prerequisites; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.prerequisites (
    capec_id character varying(255) NOT NULL,
    prerequisite character varying(8191)
);


ALTER TABLE mitre.prerequisites OWNER TO postgres;

--
-- Name: ref_tags; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.ref_tags (
    reference_id bigint NOT NULL,
    tag character varying(255)
);


ALTER TABLE mitre.ref_tags OWNER TO postgres;

--
-- Name: reference; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.reference (
    id bigint NOT NULL,
    name character varying(8191),
    refsource character varying(255),
    url character varying(8191),
    cve_id character varying(255) NOT NULL
);


ALTER TABLE mitre.reference OWNER TO postgres;

--
-- Name: reference_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.reference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.reference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.resources (
    capec_id character varying(255) NOT NULL,
    resource character varying(8191)
);


ALTER TABLE mitre.resources OWNER TO postgres;

--
-- Name: scopes; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.scopes (
    consequence_id bigint NOT NULL,
    scope character varying(255)
);


ALTER TABLE mitre.scopes OWNER TO postgres;

--
-- Name: skill; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.skill (
    id bigint NOT NULL,
    content character varying(8191),
    level character varying(255),
    capec_id character varying(255)
);


ALTER TABLE mitre.skill OWNER TO postgres;

--
-- Name: skill_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.skill ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.skill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: taxonomy_mapping; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.taxonomy_mapping (
    id bigint NOT NULL,
    entry_id character varying(255),
    entry_name character varying(255),
    mapping_fit character varying(255),
    name character varying(255),
    capec_id character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.taxonomy_mapping OWNER TO postgres;

--
-- Name: taxonomy_mapping_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.taxonomy_mapping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.taxonomy_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: techniques; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.techniques (
    attack_step_id bigint NOT NULL,
    technique character varying(8191)
);


ALTER TABLE mitre.techniques OWNER TO postgres;

--
-- Name: weakness_ordinality; Type: TABLE; Schema: mitre; Owner: postgres
--

CREATE TABLE mitre.weakness_ordinality (
    id bigint NOT NULL,
    description character varying(8191),
    ordinality character varying(255),
    cwe_id character varying(255)
);


ALTER TABLE mitre.weakness_ordinality OWNER TO postgres;

--
-- Name: weakness_ordinality_id_seq; Type: SEQUENCE; Schema: mitre; Owner: postgres
--

ALTER TABLE mitre.weakness_ordinality ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mitre.weakness_ordinality_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alternate_term alternate_term_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.alternate_term
    ADD CONSTRAINT alternate_term_pkey PRIMARY KEY (id);


--
-- Name: applicable_platform applicable_platform_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.applicable_platform
    ADD CONSTRAINT applicable_platform_pkey PRIMARY KEY (id);


--
-- Name: attack_step attack_step_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.attack_step
    ADD CONSTRAINT attack_step_pkey PRIMARY KEY (id);


--
-- Name: capec capec_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.capec
    ADD CONSTRAINT capec_pkey PRIMARY KEY (id);


--
-- Name: capec_relation capec_relation_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.capec_relation
    ADD CONSTRAINT capec_relation_pkey PRIMARY KEY (id);


--
-- Name: consequence consequence_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.consequence
    ADD CONSTRAINT consequence_pkey PRIMARY KEY (id);


--
-- Name: cpe cpe_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cpe
    ADD CONSTRAINT cpe_pkey PRIMARY KEY (id);


--
-- Name: cve cve_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve
    ADD CONSTRAINT cve_pkey PRIMARY KEY (id);


--
-- Name: cvss2 cvss2_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cvss2
    ADD CONSTRAINT cvss2_pkey PRIMARY KEY (id);


--
-- Name: cvss3 cvss3_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cvss3
    ADD CONSTRAINT cvss3_pkey PRIMARY KEY (id);


--
-- Name: cwe cwe_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe
    ADD CONSTRAINT cwe_pkey PRIMARY KEY (id);


--
-- Name: cwe_relation cwe_relation_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_relation
    ADD CONSTRAINT cwe_relation_pkey PRIMARY KEY (id);


--
-- Name: demonstrative_examp demonstrative_examp_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.demonstrative_examp
    ADD CONSTRAINT demonstrative_examp_pkey PRIMARY KEY (id);


--
-- Name: detection_method detection_method_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.detection_method
    ADD CONSTRAINT detection_method_pkey PRIMARY KEY (id);


--
-- Name: example_code example_code_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.example_code
    ADD CONSTRAINT example_code_pkey PRIMARY KEY (id);


--
-- Name: external_ref_ref external_ref_ref_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.external_ref_ref
    ADD CONSTRAINT external_ref_ref_pkey PRIMARY KEY (id);


--
-- Name: introduction introduction_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.introduction
    ADD CONSTRAINT introduction_pkey PRIMARY KEY (id);


--
-- Name: node_compl_cpe node_compl_cpe_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.node_compl_cpe
    ADD CONSTRAINT node_compl_cpe_pkey PRIMARY KEY (id);


--
-- Name: node node_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.node
    ADD CONSTRAINT node_pkey PRIMARY KEY (id);


--
-- Name: note note_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.note
    ADD CONSTRAINT note_pkey PRIMARY KEY (id);


--
-- Name: observed_example observed_example_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.observed_example
    ADD CONSTRAINT observed_example_pkey PRIMARY KEY (id);


--
-- Name: potential_mitigation potential_mitigation_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.potential_mitigation
    ADD CONSTRAINT potential_mitigation_pkey PRIMARY KEY (id);


--
-- Name: reference reference_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.reference
    ADD CONSTRAINT reference_pkey PRIMARY KEY (id);


--
-- Name: skill skill_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.skill
    ADD CONSTRAINT skill_pkey PRIMARY KEY (id);


--
-- Name: taxonomy_mapping taxonomy_mapping_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.taxonomy_mapping
    ADD CONSTRAINT taxonomy_mapping_pkey PRIMARY KEY (id);


--
-- Name: weakness_ordinality weakness_ordinality_pkey; Type: CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.weakness_ordinality
    ADD CONSTRAINT weakness_ordinality_pkey PRIMARY KEY (id);


--
-- Name: cpe_vendor_product_idx; Type: INDEX; Schema: mitre; Owner: postgres
--

CREATE INDEX cpe_vendor_product_idx ON mitre.cpe USING btree (vendor, product);


--
-- Name: techniques fk1soh3h7b6fjko74xs2lclf1xx; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.techniques
    ADD CONSTRAINT fk1soh3h7b6fjko74xs2lclf1xx FOREIGN KEY (attack_step_id) REFERENCES mitre.attack_step(id);


--
-- Name: example_code fk1yl6a5gxq1qrsr6hc02959g3l; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.example_code
    ADD CONSTRAINT fk1yl6a5gxq1qrsr6hc02959g3l FOREIGN KEY (dem_ex_id) REFERENCES mitre.demonstrative_examp(id);


--
-- Name: observed_example fk30n55esmsnhdc1n2ptc8y0ve2; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.observed_example
    ADD CONSTRAINT fk30n55esmsnhdc1n2ptc8y0ve2 FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: prerequisites fk3mtgxluficus9vuhh82pbkx8o; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.prerequisites
    ADD CONSTRAINT fk3mtgxluficus9vuhh82pbkx8o FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: alternate_term fk3tw5p2e90p2me836td5y0pw3n; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.alternate_term
    ADD CONSTRAINT fk3tw5p2e90p2me836td5y0pw3n FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: mitigations fk4juik4kysllamp4f1wd83vyt9; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.mitigations
    ADD CONSTRAINT fk4juik4kysllamp4f1wd83vyt9 FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: phases fk4t7chxxu9as5wlwe3waboes5n; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.phases
    ADD CONSTRAINT fk4t7chxxu9as5wlwe3waboes5n FOREIGN KEY (potential_mitigation_id) REFERENCES mitre.potential_mitigation(id);


--
-- Name: external_ref_ref fk65olsm4uxrdxnijpkjtojpdsn; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.external_ref_ref
    ADD CONSTRAINT fk65olsm4uxrdxnijpkjtojpdsn FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: cwe_capec fk6ovdygmh071weon17p33mhm6h; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_capec
    ADD CONSTRAINT fk6ovdygmh071weon17p33mhm6h FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: bg_details fk7dt5udon5ovj86fwc2bfp7ilt; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.bg_details
    ADD CONSTRAINT fk7dt5udon5ovj86fwc2bfp7ilt FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: introduction fk7h013741h2w51jwedy9xwrbyf; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.introduction
    ADD CONSTRAINT fk7h013741h2w51jwedy9xwrbyf FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: consequence fk7kjbqloyrva4qommg8a80nlbj; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.consequence
    ADD CONSTRAINT fk7kjbqloyrva4qommg8a80nlbj FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: affected_resources fk7xxtmddaalb1hnlc5arc6698x; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.affected_resources
    ADD CONSTRAINT fk7xxtmddaalb1hnlc5arc6698x FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: attack_step fk7ydor0d4xwvn247u9asr0k8ct; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.attack_step
    ADD CONSTRAINT fk7ydor0d4xwvn247u9asr0k8ct FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: indicators fk801eysd5jpcytcnjcqk3uk0ai; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.indicators
    ADD CONSTRAINT fk801eysd5jpcytcnjcqk3uk0ai FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: capec_relation fk8matumahubv3mw4cqhgrlea0u; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.capec_relation
    ADD CONSTRAINT fk8matumahubv3mw4cqhgrlea0u FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: cve fk99froctd1q96xb893dn64hnk4; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve
    ADD CONSTRAINT fk99froctd1q96xb893dn64hnk4 FOREIGN KEY (cvss_v3_id) REFERENCES mitre.cvss3(id);


--
-- Name: cve fk9ie96dqf2c205na5gnba0bfjk; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve
    ADD CONSTRAINT fk9ie96dqf2c205na5gnba0bfjk FOREIGN KEY (cvss_v2_id) REFERENCES mitre.cvss2(id);


--
-- Name: likelihoods fk9r32drdmam4tnj9tnhk3yiqn0; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.likelihoods
    ADD CONSTRAINT fk9r32drdmam4tnj9tnhk3yiqn0 FOREIGN KEY (consequence_id) REFERENCES mitre.consequence(id);


--
-- Name: cpe_compl_cpe fka11uua9ih7prslipy95q3vmd3; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cpe_compl_cpe
    ADD CONSTRAINT fka11uua9ih7prslipy95q3vmd3 FOREIGN KEY (cpe_id) REFERENCES mitre.cpe(id);


--
-- Name: external_ref_ref fka5dherbgqsvx1ehmxququqb0w; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.external_ref_ref
    ADD CONSTRAINT fka5dherbgqsvx1ehmxququqb0w FOREIGN KEY (dem_ex_id) REFERENCES mitre.demonstrative_examp(id);


--
-- Name: node_compl_cpe fkadsvvvrbfpsrwxb5bs5bnok8d; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.node_compl_cpe
    ADD CONSTRAINT fkadsvvvrbfpsrwxb5bs5bnok8d FOREIGN KEY (cpe_id) REFERENCES mitre.cpe(id);


--
-- Name: skill fkatsy194udbgbo0f5ltrfpibco; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.skill
    ADD CONSTRAINT fkatsy194udbgbo0f5ltrfpibco FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: taxonomy_mapping fkaypssanst11ikkjk2mka33x3n; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.taxonomy_mapping
    ADD CONSTRAINT fkaypssanst11ikkjk2mka33x3n FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: reference fkb4e53d8qxgq5qs0xixypn02vh; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.reference
    ADD CONSTRAINT fkb4e53d8qxgq5qs0xixypn02vh FOREIGN KEY (cve_id) REFERENCES mitre.cve(id);


--
-- Name: functional_areas fkc6tmxi2a207sodns86gtwgwnl; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.functional_areas
    ADD CONSTRAINT fkc6tmxi2a207sodns86gtwgwnl FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: detection_method fkcrbxeeg854ttyedo231tmnuok; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.detection_method
    ADD CONSTRAINT fkcrbxeeg854ttyedo231tmnuok FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: descriptions fkdwlrv3qge0660srojvfin5ub3; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.descriptions
    ADD CONSTRAINT fkdwlrv3qge0660srojvfin5ub3 FOREIGN KEY (cve_id) REFERENCES mitre.cve(id);


--
-- Name: ref_tags fkehe26hyy0nfjjq5fjmyu62orf; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.ref_tags
    ADD CONSTRAINT fkehe26hyy0nfjjq5fjmyu62orf FOREIGN KEY (reference_id) REFERENCES mitre.reference(id);


--
-- Name: scopes fkeqk4dacvve39eu6s00incv611; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.scopes
    ADD CONSTRAINT fkeqk4dacvve39eu6s00incv611 FOREIGN KEY (consequence_id) REFERENCES mitre.consequence(id);


--
-- Name: note fkfbu55jlellxyinodttvyf8afx; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.note
    ADD CONSTRAINT fkfbu55jlellxyinodttvyf8afx FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: cve_cwe fkfkposkqwsla5viief2dljgbax; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_cwe
    ADD CONSTRAINT fkfkposkqwsla5viief2dljgbax FOREIGN KEY (cve_id) REFERENCES mitre.cve(id);


--
-- Name: impacts fkg4gcb9trognvx8xtuh9ly08kw; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.impacts
    ADD CONSTRAINT fkg4gcb9trognvx8xtuh9ly08kw FOREIGN KEY (consequence_id) REFERENCES mitre.consequence(id);


--
-- Name: cpe_compl_cpe fkh3aaw6i6vfv4glpy53acmag0r; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cpe_compl_cpe
    ADD CONSTRAINT fkh3aaw6i6vfv4glpy53acmag0r FOREIGN KEY (compl_cpe_id) REFERENCES mitre.cpe(id);


--
-- Name: potential_mitigation fkh8in71e6354hyl4r8om10v90a; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.potential_mitigation
    ADD CONSTRAINT fkh8in71e6354hyl4r8om10v90a FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: body_texts fkhoc285tx9bejbe2tv6hl0yt3q; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.body_texts
    ADD CONSTRAINT fkhoc285tx9bejbe2tv6hl0yt3q FOREIGN KEY (demonstrative_examp_id) REFERENCES mitre.demonstrative_examp(id);


--
-- Name: consequence fkiyuk4wmvf24dw6yx1yus3s2a5; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.consequence
    ADD CONSTRAINT fkiyuk4wmvf24dw6yx1yus3s2a5 FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: node fkjh7xlvevh4eglk8ee25uaw8vf; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.node
    ADD CONSTRAINT fkjh7xlvevh4eglk8ee25uaw8vf FOREIGN KEY (cve_id) REFERENCES mitre.cve(id);


--
-- Name: cwe_relation fkjkar2iouuvifm0ibyjdksm519; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_relation
    ADD CONSTRAINT fkjkar2iouuvifm0ibyjdksm519 FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: taxonomy_mapping fkkm3jgwg7r41ymei32ma9d7okq; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.taxonomy_mapping
    ADD CONSTRAINT fkkm3jgwg7r41ymei32ma9d7okq FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: examples fkloh5hmu95kumrbem8d1yqc181; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.examples
    ADD CONSTRAINT fkloh5hmu95kumrbem8d1yqc181 FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: cwe_capec fkmkdjj0qpout9t9cs2ccqgx8vt; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cwe_capec
    ADD CONSTRAINT fkmkdjj0qpout9t9cs2ccqgx8vt FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: weakness_ordinality fkn5y9t6ulbduiuf3mmbe8sdxmi; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.weakness_ordinality
    ADD CONSTRAINT fkn5y9t6ulbduiuf3mmbe8sdxmi FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: node fkni535kidjh6jci6wtjcdw07la; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.node
    ADD CONSTRAINT fkni535kidjh6jci6wtjcdw07la FOREIGN KEY (parent_id) REFERENCES mitre.node(id);


--
-- Name: consequence_notes fkntwsqrjguh1rtd8fkadjbb40q; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.consequence_notes
    ADD CONSTRAINT fkntwsqrjguh1rtd8fkadjbb40q FOREIGN KEY (consequence_id) REFERENCES mitre.consequence(id);


--
-- Name: external_ref_ref fkobvh60wu8bulfcpfkqv61w3wk; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.external_ref_ref
    ADD CONSTRAINT fkobvh60wu8bulfcpfkqv61w3wk FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: node_compl_cpe fkp05keyvueo2v3k8b5pjl76oqc; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.node_compl_cpe
    ADD CONSTRAINT fkp05keyvueo2v3k8b5pjl76oqc FOREIGN KEY (node_id) REFERENCES mitre.node(id);


--
-- Name: applicable_platform fkp4kkwnexksbrshnngciwy29o9; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.applicable_platform
    ADD CONSTRAINT fkp4kkwnexksbrshnngciwy29o9 FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: exclude_ids fkq3kcqa04g20te9cdnsp21bt4h; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.exclude_ids
    ADD CONSTRAINT fkq3kcqa04g20te9cdnsp21bt4h FOREIGN KEY (capec_relation_id) REFERENCES mitre.capec_relation(id);


--
-- Name: cve_cwe fksu7avj0pjcgrhiu7sr9er4tyd; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.cve_cwe
    ADD CONSTRAINT fksu7avj0pjcgrhiu7sr9er4tyd FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: resources fkt3fbaihsmgymgmnn73bht25a3; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.resources
    ADD CONSTRAINT fkt3fbaihsmgymgmnn73bht25a3 FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: note fkta4moqqyeyd0i9lqjq8t7kbnu; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.note
    ADD CONSTRAINT fkta4moqqyeyd0i9lqjq8t7kbnu FOREIGN KEY (capec_id) REFERENCES mitre.capec(id);


--
-- Name: demonstrative_examp fktlwod5w3aujwd2inxoo3lkdju; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.demonstrative_examp
    ADD CONSTRAINT fktlwod5w3aujwd2inxoo3lkdju FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- Name: alternate_term fktmpr3n7fjsgx7alvxvthi1phq; Type: FK CONSTRAINT; Schema: mitre; Owner: postgres
--

ALTER TABLE ONLY mitre.alternate_term
    ADD CONSTRAINT fktmpr3n7fjsgx7alvxvthi1phq FOREIGN KEY (cwe_id) REFERENCES mitre.cwe(id);


--
-- PostgreSQL database dump complete
--

